package com.mksmcqapplicationtest.util;

import com.google.gson.Gson;
import com.mksmcqapplicationtest.R;
import com.mksmcqapplicationtest.beans.Child;
import com.mksmcqapplicationtest.beans.Class;
import com.mksmcqapplicationtest.beans.Student;

import java.util.ArrayList;
import java.util.List;

public class AppUtility {

    public static int ClassTotalFees;
    public static boolean IsFirstTimeHome = false;
    public static boolean IsFirstAudio = false;

    public static String App_Name = "MKS MCQ APP";
    public static String PackageName = "";
    public static String StorePDFPath = App_Name + "/MCQExamQuestionPaper";
    public static String ProgressDialogType = "Circle";
    public static int ProgressDialogColor = R.color.White;
    public static String VIDEO_ID = "";
    public static String SELECTED_CLASS_DATAMASTER = "";
    public static String SELECTED_DATANAME_DATAMASTER = "";
    public static String PROFILE = "";
    public static Boolean Result;
    public static String IsTeacher = "T";
    public static String MASTERCODE = "";
    public static int KEY_DURATION;
    public static int KEY_WIDTH;
    public static int KEy_HEIGHT;
    public static int SEARCH = 0;
    public static String KEY_USERNAME = "9762616197";
    public static String KEY_CLASSCODE = "1";
    public static String KEY_CLASSNAME = "";
    public static String KEY_STUDENTCODE = "1";
    public static String KEY_TEACHERCODE = "";
    public static String KEY_STUDENTNAME = "Master Key Solution";
    public static String KEY_PASSWORD = "";
    public static String KEY_NEW_PASSWORD = "";
    public static String KEY_TEST_SUBMIT_TIME = "";
    public static final String KEY_TEST_SUBMIT = "testSubmit";
    public static final String KEY_TEST_ATTEMPT = "attempt";
    public static String DataText = "";
    public static String ImagePath = "";
    public static String VideoPath = "";
    public static String PDFPath = "";
    public static String KEY_TITLE = App_Name;
    public static String KEY_TEST_ID = "testId";
    public static final String KEY_TEST_NAME = "testName";
    public static String KEY_ATTENDANCE;
    public static String SELECT_ALL_IS_CHECKED = "P";
    public static String[] ClassName = new String[0];
    public static String[] StudentCode = new String[0];
    public static String[] StudentName = new String[0];
    public static int KEY_SEND_NOTIFICATION_CHECK_BOX_CHECKED_COUNT;
    public static String[] ClassCode = new String[0];
    public static int KEY_ATTENDANCE_CHECK_BOX_CHECKED_COUNT;
    public static List<Class> CLASS_RESPONSE = new ArrayList<>();
    public static List<Student> STUDENT_RESPONSE = new ArrayList<>();
    public static List<Student> IndividualListResponse = new ArrayList<>();
    public static String[] arraylist = new String[0];
    public static String[] arraylistMarksAfterChange = new String[0];
    public static String[] arraylistChangeMarks = new String[0];
    public static String ROOT_FOLDERPATH = "";
    //        public static final String baseUrl = "http://DrSolatBiologyAcademy.masterkeysolution.in/";
//            public static final String baseUrl = "http://palwebiologyclasses.masterkeysolution.in/";
//    public static final String baseUrl = "http://chanakyacoachingclasses.masterkeysolution.in/";
//    public static final String baseUrl = "http://toshniwaltutorials.masterkeysolution.in/";
//        public static final String baseUrl = "http://MKSPayalTesting1.masterkeysolution.in/";
        public static final String baseUrl = "http://MKSPayalTesting9.masterkeysolution.in/";
//            public static final String baseUrl = "http://192.168.1.102/SolatBiologyClasses/";
    public static final String LetUsCbaseUrl = "http://LetUsC.masterkeysolution.in/";
    public static final String LOGIN_URL = baseUrl + "MCQServices/MCQService.svc/PostLogin";
    public static final String EXAMLIST_URL = baseUrl + "/MCQServices/MCQService.svc/PostTestList";
    public static final String QUESTION_URL = baseUrl + "/MCQServices/MCQService.svc/PostTest";
    public static final String SUBMIT_TEST_URL = baseUrl;
    public static final String CHANGE_PASSWORD_URL = baseUrl + "/MCQServices/MCQService.svc/PostChangePassword";
    public static final String SYNCHRONIZATION_URL = baseUrl + "/MCQServices/MCQService.svc/PostTestResult";

    public static String GET_CLASS_DATA = baseUrl + "/MCQServices/MCQService.svc/PostDataForClass";
    public static String GET_DATA_OF_CLASS = baseUrl + "/MCQServices/MCQService.svc/PostDataOfClass";

    public static String GET_TEST_DATA = baseUrl + "/MCQServices/MCQService.svc/PostDataForTest";
    public static String GET_DATA = baseUrl + "/MCQServices/MCQService.svc/PostData";
    public static String GET_CLASS_NAME_LIST = baseUrl + "/MCQServices/MCQService.svc/PostClassName";
    public static String GET_STUDENT_NAME_LIST = baseUrl + "/MCQServices/MCQService.svc/PostStudentName";
    public static String GET_STUDENT_LIST_WITH_MARKS = baseUrl + "/MCQServices/MCQService.svc/PostStudentListWithTestMarks";
    public static final String MARK_ATTENDANCE = baseUrl + "/MCQServices/MCQService.svc/MarkAttendance";
    public static final String ATTENDANCE_REPORT_URL = baseUrl + "/MCQServices/MCQService.svc/AttendanceReport";
    public static final String FEES_URL = baseUrl + "/MCQServices/MCQService.svc/PostShowFees";
    public static final String FEES_FOR_STUDENT_URL = baseUrl + "/MCQServices/MCQService.svc/PostShowFeesForStudent";
    public static final String GIVEN_TEST_LIST_URL = baseUrl + "/MCQServices/MCQService.svc/PostGivenTestList";
    public static final String GIVEN_TEST_QUESTION_URL = baseUrl + "/MCQServices/MCQService.svc/PostGivenTestQuestion";
    public static final String ADD_FEES_URL = baseUrl + "/MCQServices/MCQService.svc/PostAddFees";
    public static final String ADD_TIME_TABLE_URL = baseUrl + "/MCQServices/MCQService.svc/PostAddTimeTable";
    public static final String DETAIL_FEES_URL = baseUrl + "/MCQServices/MCQService.svc/PostDetailsOfFees";
    public static final String SHOW_TIME_TABLE_URL = baseUrl + "/MCQServices/MCQService.svc/PostGetTimeTable";
    public static final String ENABLE_DISABLE_DATA = baseUrl + "/MCQServices/MCQService.svc/PostUpdateDataForClass";
    public static final String ENABLE_DISABLE_TEST = baseUrl + "/MCQServices/MCQService.svc/PostUpdateTest";
    public static final String ENABLE_DISABLE_STUDENT = baseUrl + "/MCQServices/MCQService.svc/PostUpdateStudent";
    public static final String GET_ALL_STUDENT_FOR_ENABLE = baseUrl + "/MCQServices/MCQService.svc/PostAllStudentName";
    public static final String POST_SHOW_NOTIFICATION_URL = baseUrl + "/MCQServices/MCQService.svc/PostShowNotification";
    public static String GET_ALL_STUDENT_NAME_LIST = baseUrl + "/MCQServices/MCQService.svc/PostAllStudentList";
    public static final String SEND_NOTIFICATION_FROM_TEACHER = baseUrl + "/MCQServices/MCQService.svc/PostSendNotificationFromTeacher";
    public static final String UPDATE_NOTIFICATION = baseUrl + "/MCQServices/MCQService.svc/PostUpdateNotification";
    public static final String GET_PROFILE = baseUrl + "/MCQServices/MCQService.svc/PostProfile";
    public static final String UPDATE_PROFILE = baseUrl + "/MCQServices/MCQService.svc/PostUpdateProfile";
    public static final String UPLOAD_MASTER_DATA = baseUrl + "/MCQServices/MCQService.svc/PostUploadData";
    public static final String UPLOAD_STUDENT_ANSWERSHEET = baseUrl + "/MCQServices/MCQService.svc/PostSendStudentAnswerSheet";
    public static final String SHOW_STUDENT_ANSWERSHEET = baseUrl + "/MCQServices/MCQService.svc/PostShowStudentAnswerSheet";
    public static final String GET_NOTICE = baseUrl + "/MCQServices/MCQService.svc/PostGetNotice";
    public static String GET_AUDIO_LIST = baseUrl + "/MCQServices/MCQService.svc/PostGetAudioList";
    public static final String ENABLE_DISABLE_AUDIO = baseUrl + "/MCQServices/MCQService.svc/PostUpdateAudioFlag";
    public static String Guest_GET_CLASS_DATA = baseUrl + "/MCQServices/MCQService.svc/PostDataForGuest";
    public static final String ENABLE_DISABLE_DATA_Guest = baseUrl + "/MCQServices/MCQService.svc/PostUpdateGuestDataForClass";
    public static String GET_Guest_DATA_OF_CLASS = baseUrl + "/MCQServices/MCQService.svc/PostGuestDataOfClass";
    public static String Guest_GET_AUDIO_LIST = baseUrl + "/MCQServices/MCQService.svc/PostGetGuestAudioList";
    public static final String Guest_ENABLE_DISABLE_AUDIO = baseUrl + "/MCQServices/MCQService.svc/PostUpdateGuestAudioFlag";
    public static final Gson GSON = new Gson();
    public static String SIGNUP_FOR_GUEST = baseUrl + "/MCQServices/MCQService.svc/PostGuestRegistration";
    public static final String GET_ALL_GUEST_FOR_ENABLE = baseUrl + "/MCQServices/MCQService.svc/PostAllGuest";
    public static String INDIVIDUAL_REPORT_URL = baseUrl + "/MCQServices/MCQService.svc/DayWiseReport";
    public static final String VIDEO_MANUAL = baseUrl + "/MCQServices/MCQService.svc/PostVideoManualList";
    public static final String MOVE_DATA = baseUrl + "/MCQServices/MCQService.svc/PostChangeClassOfData";
    public static final String MOVE_Student = baseUrl + "/MCQServices/MCQService.svc/PostChangeClassOfStudent";
    public static final String CLEAR_NOTIFICATON = baseUrl + "/MCQServices/MCQService.svc/PostClearNotification";
    public static String GET_CLASS_EXTRA_DATA = baseUrl + "/MCQServices/MCQService.svc/PostClassDataOrExtraData";
    public static String SEND_QUERY_URL = baseUrl + "/MCQServices/MCQService.svc/PostSendQuery";
    public static String UPDATE_QUERY = baseUrl + "/MCQServices/MCQService.svc/PostUpdateQuery";
    public static String GET_QUERY = baseUrl + "/MCQServices/MCQService.svc/PostGetQuery";
    public static String GET_DATA_OF_CLASS_FOR_GUEST = baseUrl + "/MCQServices/MCQService.svc/PostDataOfClassForGuest";
    public static String GET_ALL_TEST_LIST = baseUrl + "/MCQServices/MCQService.svc/PostGetListOfTest";
    public static String OTP_VERIFICATION_URL = baseUrl + "/MCQServices/MCQService.svc/PostOTPVerification";
    public static String RESEND_OTP_URL = baseUrl + "/MCQServices/MCQService.svc/PostReSendOTPMail";
    public static String SETTING_URL = baseUrl + "/MCQServices/MCQService.svc/PostSetting";
    public static String SEND_THEORY_TEST_MARKS = baseUrl + "/MCQServices/MCQService.svc/PostTheoryTestMarks";
    public static String FORGOT_PASSWORD = baseUrl + "/MCQServices/MCQService.svc/PostForgotPassword";
    public static String UPDATE_CHECK = baseUrl + "/MCQServices/MCQService.svc/PostCheckForUpdate";
    public static String ADD_THEORY_TEST = baseUrl + "/MCQServices/MCQService.svc/PostAddTheoryTest";
    public static String GET_GROUP_MENU = baseUrl + "/MCQServices/MCQService.svc/PostGetGroupMenu";
    public static String GET_CHILD_MENU = baseUrl + "/MCQServices/MCQService.svc/PostGetChildMenu";
    public static String GET_ADVERTISE_PARAMETER = baseUrl + "/MCQServices/MCQService.svc/PostAdvertiseVisibility";
    public static String REFERENCE_APP = LetUsCbaseUrl + "/Services/Service.svc/PostReferenceApp";
    public static String GET_UNIVERSITY_NAME_LIST = baseUrl + "/MCQServices/MCQService.svc/PostGetUniversity";
    public static String ABOUT_US_URL = baseUrl + "/MCQServices/MCQService.svc/PostAboutUs";
    public static String GET_IMEI = baseUrl + "/MCQServices/MCQService.svc/PostGetIMEI";
    public static String MASTER_ADD_TEST = baseUrl + "/MCQServices/MCQService.svc/PostAddTest";
    public static String MASTER_ADD_QUESTION = baseUrl + "/MCQServices/MCQService.svc/PostAddQuestion";
    public static String MASTER_GET_CATEGORY = baseUrl + "/MCQServices/MCQService.svc/PostGetCategory";
    public static String MASTER_GET_QUESTION = baseUrl + "/MCQServices/MCQService.svc/PostGetQuestion";
    public static String MASTER_GET_TESTNAME = baseUrl + "/MCQServices/MCQService.svc/PostGetTest";
    public static String MASTER_PREPARE_TEST = baseUrl + "/MCQServices/MCQService.svc/PostPrepareTest";

    public static Boolean IsAdvertiesVisible = false;
    public static Boolean AboveIsAdvertiesVisible = true;
    public static Boolean IsAdvertiesVisibleForGuest = true;
    public static Boolean ShowAndUploadAnswerSheerVisible = false;
    public static Boolean IsDemoApplication = false;
    public static String AudioFilesURL = "";

    public static List<Child> childResponse;
    public static int TheroyTest_ShortCut = 1;
    public static int MCQTest_ShortCut = 0;
    public static int SpokenEnglish_ShortCut = 0;
    public static int ShowAttendance_ShortCut = 0;
    public static int TabMoveGuest = 0;
    public static int TabMoveStudent = 0;
    public static int TabMoveTheoryTest = 0;
    public static List<String> groupcodearraylist = new ArrayList<String>();


    //    EnglishSpeking
    public static String EnglishBaseUrl = "http://192.168.1.102/EglishSpeaking/";
//    public static String EnglishBaseUrl = "http://SpokenEnglish.masterkeysolution.in/";
    public static String GET_AUDIO_LIST_ENGLISH_SPEAKING = EnglishBaseUrl + "/MCQServices/MCQService.svc/PostGetAudioList";
    public static String GET_LEVELS = EnglishBaseUrl + "/MCQServices/MCQService.svc/PostLevel";
    public static String GET_ALL_TEST_LIST_ENGLISH_SPEAKING = EnglishBaseUrl + "/MCQServices/MCQService.svc/PostTestList";
    public static final String GIVEN_TEST_LIST_URL_ENGLISH_SPEAKING = EnglishBaseUrl + "/MCQServices/MCQService.svc/PostGivenTestList";
    public static final String GIVEN_TEST_QUESTION_URL_ENGLISH_SPEAKING = EnglishBaseUrl + "/MCQServices/MCQService.svc/PostGivenTestQuestion";
    public static final String TEST_RESULT_URL = EnglishBaseUrl + "/MCQServices/MCQService.svc/PostTestResult";
    public static final String QUESTION_URL_ENGLISH_SPEAKING = EnglishBaseUrl + "/MCQServices/MCQService.svc/PostTest";
    public static String Level = "";
    public static Boolean PassingCriteria = false;


    public static String Mobile_IMEI_CODE = "";
    public static final int PERMISSION_REQUEST_CODE = 1;
}

